version: 2.1 # Use version 2.1 to enable Orb usage.
orbs:
  win: circleci/windows@2.2.0 # The Windows orb give you everything you need to start using the Windows executor.
jobs:
  unit_tests:
    docker:
      - image: python:3.7.3
    steps:
      - run:
          name: Run unit tests
          command: echo "Run unit test"
  integration_tests:
    executor: win/default
    steps:
      - checkout:
      - run: git clone git@github.com:Lannt-teko/ppm-api-testing.git
      - restore_cache:
          key: pip-{{checksum "requirements.txt"}}
      - run: python -m pip install --upgrade pips
      - run:
          name: Install requirements
          command: pip install -r requirements.txt
      - save_cache:
          key: pip-{{checksum "requirements.txt"}}
          paths:
            - ~/.cache/pip
      - run:
          name: Setup environment variables
          command: cp .env.test .env
      - run:
          name: Run tests
          command: pytest --submit-tests ppm-api-testing/tests/functional/price/test_create_overlap_price_schedule.py
workflows:
  unit_tests:
    jobs:
      - unit_tests
      - integration_tests
