version: 2.1 # Use version 2.1 to enable Orb usage.
orbs:
  win: circleci/windows@2.2.0 # The Windows orb give you everything you need to start using the Windows executor.

jobs:
  unit_tests:
    working_directory: ~/backend_app
    docker:
      - image: python:3.7.3
    steps:
      - run:
          name: Run unit tests
          command: echo "Run unit test"
  integration_tests:
    executor: win/default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "1e:58:d1:86:72:f0:52:b3:e0:b2:5c:03:fe:79:89:86"
      - run:
          name: Clone test code
          command:
            git clone git@github.com:Lannt-teko/ppm-api-testing.git
      #      - restore_cache:
      #          key: pip-{{checksum "requirements.txt"}}
      #      - run: python -m pip install --upgrade pips
      - run:
          name: Install requirements
          command: >-
            cd ppm-api-testing
            pip install -r requirements.txt
      #      - save_cache:
      #          key: pip-{{checksum "requirements.txt"}}
      #          paths:
      #            - ~/.cache/pip
      #      - run:
      #          name: Setup environment variables
      #          command: cp .env.test .env
      - run:
          name: Run tests
          command: pytest --submit-tests tests/functional/price/test_create_overlap_price_schedule.py
workflows:
  unit_tests:
    jobs:
      - unit_tests
  integration_tests:
    jobs:
      - integration_tests
